INSERT INTO incidents (datetime, status, judgment, content, assignee, priority, from_email, to_email, sender, subject) VALUES
('2024-10-15 14:30:00', '調査中', '静観', 'データベースサーバーへの接続が突然失われました。アプリケーションがデータを取得・保存できない状態です。緊急対応が必要です。', '', '高', 'alert@system.incidenttools.com', 'support@incidenttools.com', 'CTC', '【緊急】データベース接続エラー'),
('2024-10-16 09:15:00', '解決済み', '要対応', 'ネットワーク機器の障害によりサービスが一時的にダウンしました。', 'john.doe@example.com', '中', 'monitor@network.com', 'it-team@example.com', 'Zabbix', 'ネットワーク障害アラート'),
('2024-10-17 11:45:00', '未着手', '静観', '新しいソフトウェアアップデートによる互換性の問題が報告されています。', '', '低', 'updates@software.com', 'tech-support@example.com', 'Avaya', 'ソフトウェア互換性の問題'),
('2024-10-18 16:20:00', '調査中', '要対応', 'セキュリティ監査で複数の脆弱性が検出されました。早急な対応が必要です。', 'sarah.smith@example.com', '高', 'security@audit.com', 'security-team@example.com', 'CTC', '【重要】セキュリティ脆弱性検出'),
('2024-10-19 08:00:00', '解決済み', '静観', 'バックアップシステムの定期チェックで異常が見つかりました。', 'mike.johnson@example.com', '中', 'backup@system.com', 'admin@example.com', 'Zabbix', 'バックアップシステム異常'),
('2024-10-20 13:10:00', '未着手', '要対応', 'ユーザーからアプリケーションのパフォーマンス低下の報告が多数届いています。', '', '高', 'user-support@app.com', 'dev-team@example.com', 'Avaya', 'アプリケーションパフォーマンス低下'),
('2024-10-21 10:30:00', '調査中', '静観', 'サーバールームの空調システムに問題が発生し、温度が上昇しています。', 'alex.brown@example.com', '中', 'facility@building.com', 'it-ops@example.com', 'CTC', 'サーバールーム温度上昇警告'),
('2024-10-22 15:45:00', '解決済み', '要対応', 'ファイアウォールの設定ミスにより、一部のサービスにアクセスできない状況が発生しました。', 'emily.wilson@example.com', '高', 'network@security.com', 'network-admin@example.com', 'Zabbix', 'ファイアウォール設定エラー'),
('2024-10-23 09:20:00', '未着手', '静観', 'データセンターの電源システムに不安定な動作が見られます。', '', '中', 'datacenter@power.com', 'facility-manager@example.com', 'Avaya', 'データセンター電源システム不安定'),
('2024-10-24 14:00:00', '調査中', '要対応', 'クラウドストレージサービスでデータ同期の遅延が発生しています。', 'david.lee@example.com', '低', 'cloud-support@storage.com', 'cloud-team@example.com', 'CTC', 'クラウドストレージ同期遅延'),
('2024-10-25 11:30:00', '解決済み', '静観', 'メールサーバーのスパムフィルターが正常に機能していない可能性があります。', 'lisa.taylor@example.com', '中', 'mail-admin@server.com', 'security@example.com', 'Zabbix', 'メールスパムフィルター異常'),
('2024-10-26 17:15:00', '未着手', '要対応', 'ウェブサイトの一部ページでSSL証明書のエラーが表示されています。', '', '高', 'ssl-monitor@web.com', 'web-admin@example.com', 'Avaya', 'SSL証明書エラー'),
('2024-10-27 08:45:00', '調査中', '静観', 'バッチジョブの実行に異常な遅延が発生しています。', 'robert.miller@example.com', '中', 'batch@system.com', 'dev-ops@example.com', 'CTC', 'バッチジョブ遅延'),
('2024-10-28 12:00:00', '解決済み', '要対応', 'ユーザー認証システムで断続的なエラーが発生しています。', 'jennifer.moore@example.com', '高', 'auth@system.com', 'security-ops@example.com', 'Zabbix', 'ユーザー認証エラー'),
('2024-10-29 10:10:00', '未着手', '静観', 'データベースのインデックス再構築中にパフォーマンス低下が観測されました。', '', '低', 'db-monitor@system.com', 'dba@example.com', 'Avaya', 'DB インデックス再構築影響'),
('2024-10-30 16:30:00', '調査中', '要対応', 'APIゲートウェイでレート制限エラーが多発しています。', 'chris.anderson@example.com', '中', 'api@gateway.com', 'api-team@example.com', 'CTC', 'APIレート制限エラー'),
('2024-10-31 09:00:00', '解決済み', '静観', 'バックアップジョブが予定時刻に開始されませんでした。', 'karen.white@example.com', '高', 'backup@system.com', 'it-ops@example.com', 'Zabbix', 'バックアップジョブ未開始'),
('2024-11-01 13:45:00', '未着手', '要対応', 'ログ収集サーバーのディスク容量が危険水準に達しています。', '', '中', 'log@monitor.com', 'storage-admin@example.com', 'Avaya', 'ログサーバーディスク容量警告'),
('2024-11-02 11:20:00', '調査中', '静観', 'セキュリティスキャンで新たな脆弱性が検出されました。', 'tom.harris@example.com', '高', 'security@scan.com', 'security-team@example.com', 'CTC', '新規セキュリティ脆弱性検出'),
('2024-11-03 15:00:00', '解決済み', '要対応', 'ロードバランサーの設定に問題があり、トラフィックが適切に分散されていません。', 'nancy.clark@example.com', '中', 'lb@network.com', 'network-ops@example.com', 'Zabbix', 'ロードバランサー設定エラー'),
('2024-11-04 08:30:00', '未着手', '静観', 'データウェアハウスの ETL プロセスが異常終了しました。', '', '低', 'etl@datawarehouse.com', 'data-team@example.com', 'Avaya', 'ETL プロセス異常終了'),
('2024-11-05 14:15:00', '調査中', '要対応', 'コンテナオーケストレーションシステムでノードの自動スケーリングが機能していません。', 'peter.young@example.com', '高', 'container@orchestration.com', 'devops@example.com', 'CTC', 'コンテナ自動スケーリング不具合'),
('2024-11-06 10:45:00', '解決済み', '静観', 'CDNキャッシュの更新に遅延が発生しています。', 'susan.walker@example.com', '中', 'cdn@provider.com', 'web-ops@example.com', 'Zabbix', 'CDNキャッシュ更新遅延'),
('2024-11-07 16:50:00', '未着手', '要対応', 'サードパーティ認証サービスとの連携に断続的な問題が発生しています。', '', '高', 'auth@thirdparty.com', 'integration-team@example.com', 'Avaya', 'サードパーティ認証連携エラー'),
('2024-11-08 09:30:00', '調査中', '静観', 'ビジネスインテリジェンスツールのレポート生成に異常な遅延が発生しています。', 'mark.evans@example.com', '低', 'bi@reporting.com', 'bi-team@example.com', 'CTC', 'BIレポート生成遅延'),
('2024-11-09 12:40:00', '解決済み', '要対応', 'データベースのミラーリングプロセスが失敗し、レプリケーションに遅れが生じています。', 'olivia.green@example.com', '高', 'db@replication.com', 'dba@example.com', 'Zabbix', 'DBレプリケーション遅延'),
('2024-11-10 08:15:00', '未着手', '静観', 'モニタリングシステムからの通知メールが届いていない可能性があります。', '', '中', 'monitor@alerts.com', 'monitoring-team@example.com', 'Avaya', 'モニタリング通知未達'),
('2024-11-11 13:20:00', '調査中', '要対応', 'クラウドサービスの料金が急激に上昇しています。異常な使用状況の可能性があります。', 'daniel.brown@example.com', '高', 'billing@cloud.com', 'finance@example.com', 'CTC', 'クラウド使用料金異常'),
('2024-11-12 11:00:00', '解決済み', '静観', 'サーバーの自動パッチ適用プロセスが一部のサーバーで失敗しました。', 'emma.davis@example.com', '中', 'patch@management.com', 'system-admin@example.com', 'Zabbix', 'パッチ適用失敗');