services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: new
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  datastore:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    command: gcloud beta emulators datastore start --host-port=0.0.0.0:8090 --project=local-project --consistency=1.0
    environment:
      - DATASTORE_PROJECT_ID=local-project
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8090
    ports:
      - "8090:8090"
networks:
  app-network:

volumes:
  db_data:
